# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6Qf9U8jQIgpVLtbf6b7coH2dG0f_nBu
"""

import streamlit as st
import pandas as pd
import joblib


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="Dry Bean Variety Classification",
    page_icon="🌱",
    layout="wide"
)


# --------------------------------------------------
# Load Saved Machine Learning Objects
# --------------------------------------------------

@st.cache_resource
def load_models():

    model = joblib.load("logistic_model.pkl")
    selector = joblib.load("feature_selector.pkl")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")

    return model, selector, scaler, label_encoder


model, selector, scaler, le = load_models()


# --------------------------------------------------
# Title
# --------------------------------------------------

st.title("🌱 Dry Bean Variety Classification")

st.write(
    "This application predicts the variety of a dry bean "
    "using its physical characteristics."
)

st.info(
    "Model used: Tuned Logistic Regression | "
    "Feature Selection: SelectKBest | "
    "Scaling: StandardScaler"
)


# --------------------------------------------------
# Input Features
# --------------------------------------------------

st.subheader("Enter Bean Measurements")


features = [
    "Area",
    "Perimeter",
    "MajorAxisLength",
    "MinorAxisLength",
    "AspectRation",
    "Eccentricity",
    "ConvexArea",
    "EquivDiameter",
    "Extent",
    "Solidity",
    "roundness",
    "Compactness",
    "ShapeFactor1",
    "ShapeFactor2",
    "ShapeFactor3",
    "ShapeFactor4"
]


# --------------------------------------------------
# Create Input Fields
# --------------------------------------------------

input_data = {}

col1, col2 = st.columns(2)

for i, feature in enumerate(features):

    if i % 2 == 0:

        with col1:

            input_data[feature] = st.number_input(
                feature,
                min_value=0.0,
                value=0.0,
                format="%.6f"
            )

    else:

        with col2:

            input_data[feature] = st.number_input(
                feature,
                min_value=0.0,
                value=0.0,
                format="%.6f"
            )


# --------------------------------------------------
# Prediction
# --------------------------------------------------

if st.button("🔮 Predict Bean Variety", use_container_width=True):

    # Convert user input into DataFrame
    input_df = pd.DataFrame([input_data])

    try:

        # Step 1: Feature Selection
        input_selected = selector.transform(input_df)

        # Step 2: Feature Scaling
        input_scaled = scaler.transform(input_selected)

        # Step 3: Prediction
        prediction = model.predict(input_scaled)

        # Convert encoded class back to original class name
        predicted_class = le.inverse_transform(prediction)[0]

        # --------------------------------------------------
        # Display Prediction
        # --------------------------------------------------

        st.success(
            f"🌱 Predicted Bean Variety: **{predicted_class}**"
        )

        # --------------------------------------------------
        # Prediction Probability
        # --------------------------------------------------

        if hasattr(model, "predict_proba"):

            probabilities = model.predict_proba(input_scaled)[0]

            probability_df = pd.DataFrame({
                "Bean Variety": le.classes_,
                "Probability": probabilities
            })

            probability_df["Probability"] = (
                probability_df["Probability"] * 100
            ).round(2)

            probability_df = probability_df.sort_values(
                "Probability",
                ascending=False
            )

            st.subheader("Prediction Probabilities")

            st.dataframe(
                probability_df,
                use_container_width=True,
                hide_index=True
            )

    except Exception as e:

        st.error(
            "Prediction failed. Please check the input values."
        )

        st.exception(e)


# --------------------------------------------------
# Project Information
# --------------------------------------------------

st.divider()

st.subheader("About the Project")

st.write(
    """
    This project classifies seven varieties of dry beans using
    machine learning based on their physical characteristics.

    The final model is a tuned Logistic Regression classifier.
    Feature selection was performed using SelectKBest with ANOVA
    F-test, followed by StandardScaler normalization.
    """
)

st.caption(
    "Dry Bean Variety Classification using Machine Learning"
)
